### ISSUE TITLE
Where is tso code?

### ISSUE THREAD

**Issue by aparo** [oyvindberg/ScalablyTyped#23]
Hi,
 I want to contribe updating some libraries (ie highcharts, elasticsearch ) or adding more (ie. highcharts-react, ...).
How can I start? There is no enough hints to start to help you.

**Comment by oyvindberg** [comment]
Hey there! Thanks for your interest in helping out! The tso source code is not open source yet, but will be soon (weeks/months), probably when I declare the first stable version of ScalablyTyped. If you have experience/interest in writing compilers and some time I can invite you early, but otherwise I would rather appreciate help in writing facades or demos, and receiving feedback on the generated code in this early stage.

As for adding libraries just pop by gitter and ask, and I'll add them to the build:)

**Comment by oyvindberg** [comment]
I added `highcharts-react-official`, `@elastic/elasticsearch` and updated `highcharts` to use the first party definitions instead of the old ones in DefinitelyTyped. Feel free to have a look tomorrow after it publishes

**Comment by aparo** [comment]
Thanks a lot.
I'll test them.
