### ISSUE TITLE
null instead if undefined in apply of companion object

### ISSUE THREAD

**Issue by an-tex** [oyvindberg/ScalablyTyped#26]
Looking at `typings.antd.libButtonButtonMod.ButtonProps`, the trait looks like this
```scala
trait ButtonProps extends js.Object {
  var about: js.UndefOr[String] = js.undefined
  var accessKey: js.UndefOr[String] = js.undefined
  var `aria-activedescendant`: js.UndefOr[String] = js.undefined
  var `aria-atomic`: js.UndefOr[Boolean] = js.undefined
[...]
```

But the companion object looks like this:
```scala
object ButtonProps {
  @scala.inline
  def apply(
    about: String = null,
    accessKey: String = null,
    `aria-activedescendant`: String = null,
    `aria-atomic`: js.UndefOr[Boolean] = js.undefined,
```

So most parameters default to `null` (except for `Boolean` type) instead of `js.undefined`. I guess they should all be `js.Undef.Or[T] = js.undefined` ?

**Comment by oyvindberg** [comment]
Hi there, and thanks for your interest :)

What you see here is as designed, though I'm definitely open to suggestions if any of it is cumbersome/wrong somehow.

If you look further down in the method you'll see 
```scala
val __obj = js.Dynamic.literal()
if (about != null) __obj.updateDynamic("about")(about)
...
```
In other words we only set the value if it's not null. The scala optimizer/inliner ensures that all the parameters which are defaulted to `null` (as well as the method itself) are erased from the final javascript code.

I spent some effort making sure these traits are `new`able, as long as they're not annotated with `@js.native`. Creating javascript objects with `new` is very flexible, but somewhat irritating (different syntax for vars/vals, handling overrides, type inference is not always what you want).

For that reason I came up with these creator methods, which ensures normal method syntax for creating objects. In order to make them as user-friendly as possible (and to ensure the inliner can do it's part), I chose to use `null` rather than `js.UndefOr`. The reason is that this avoids a bunch of common type inference issues, especially those caused by needing two implicit conversions. It also looks cleaner in your IDE when you query which types things are and so on. When you see that for instance `Boolean` falls back to `js.UndefOr` it's because `null` is not a valid value for primitives on the JVM.

The creator methods in their current form have some drawbacks as well. 
- Primarily if you already have an `val about: js.UndefOr[String]` and you want to create an `ButtonProps` in this particular case, there is no way to use them. This is thought to be uncommon enough that it's ok to fallback to `new ButtonProps{...}` in that case. 
- Heavy use of creator methods will probably cause some pressure on the optimizer (causing longer compiles), and you might bump into JVM limits of method body length(!) because all the `null` parameters are kept there. All in all it's a fairly difficult compromise, especially for traits like `ButtonProps` which has insanely many props.

As a final note, there is always the fallback option of using `js.Dynamic` and casting.

Hope this helps, I'll try to rewrite this and put it into the documentation in the readme file.

**Comment by an-tex** [comment]
Hi! Thanks for the quick reply. It looks a bit strange at the first look at the method parameters but after playing around myself it seems to make sense (especially due to the two implicit conversions). The whole JS interop especially for big libraries like Ant is a complex beast. Ticket can be closed, thanks!
